'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4200.
'
Namespace VR_searchengine
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SearchEngineSoap", [Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class SearchEngine
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private fetchNextLocationsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fetchSearchCriteriaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fetchSearchResultsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private saveSearchQueryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fetchPropertyDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fetchLocationDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.internalWebServices.My.MySettings.Default.internalWebServices_VR_searchengine_SearchEngine
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event fetchNextLocationsCompleted As fetchNextLocationsCompletedEventHandler
        
        '''<remarks/>
        Public Event fetchSearchCriteriaCompleted As fetchSearchCriteriaCompletedEventHandler
        
        '''<remarks/>
        Public Event fetchSearchResultsCompleted As fetchSearchResultsCompletedEventHandler
        
        '''<remarks/>
        Public Event saveSearchQueryCompleted As saveSearchQueryCompletedEventHandler
        
        '''<remarks/>
        Public Event fetchPropertyDataCompleted As fetchPropertyDataCompletedEventHandler
        
        '''<remarks/>
        Public Event fetchLocationDataCompleted As fetchLocationDataCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/SearchEngine/fetchNextLocations", RequestNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", ResponseNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fetchNextLocations(ByVal searchType As Integer, ByVal parentRef As Integer) As childLocations
            Dim results() As Object = Me.Invoke("fetchNextLocations", New Object() {searchType, parentRef})
            Return CType(results(0),childLocations)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fetchNextLocationsAsync(ByVal searchType As Integer, ByVal parentRef As Integer)
            Me.fetchNextLocationsAsync(searchType, parentRef, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fetchNextLocationsAsync(ByVal searchType As Integer, ByVal parentRef As Integer, ByVal userState As Object)
            If (Me.fetchNextLocationsOperationCompleted Is Nothing) Then
                Me.fetchNextLocationsOperationCompleted = AddressOf Me.OnfetchNextLocationsOperationCompleted
            End If
            Me.InvokeAsync("fetchNextLocations", New Object() {searchType, parentRef}, Me.fetchNextLocationsOperationCompleted, userState)
        End Sub
        
        Private Sub OnfetchNextLocationsOperationCompleted(ByVal arg As Object)
            If (Not (Me.fetchNextLocationsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fetchNextLocationsCompleted(Me, New fetchNextLocationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/SearchEngine/fetchSearchCriteria", RequestNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", ResponseNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fetchSearchCriteria(ByVal UniqueKey As String) As searchCriteria
            Dim results() As Object = Me.Invoke("fetchSearchCriteria", New Object() {UniqueKey})
            Return CType(results(0),searchCriteria)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fetchSearchCriteriaAsync(ByVal UniqueKey As String)
            Me.fetchSearchCriteriaAsync(UniqueKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fetchSearchCriteriaAsync(ByVal UniqueKey As String, ByVal userState As Object)
            If (Me.fetchSearchCriteriaOperationCompleted Is Nothing) Then
                Me.fetchSearchCriteriaOperationCompleted = AddressOf Me.OnfetchSearchCriteriaOperationCompleted
            End If
            Me.InvokeAsync("fetchSearchCriteria", New Object() {UniqueKey}, Me.fetchSearchCriteriaOperationCompleted, userState)
        End Sub
        
        Private Sub OnfetchSearchCriteriaOperationCompleted(ByVal arg As Object)
            If (Not (Me.fetchSearchCriteriaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fetchSearchCriteriaCompleted(Me, New fetchSearchCriteriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/SearchEngine/fetchSearchResults", RequestNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", ResponseNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fetchSearchResults(ByVal UniqueKey As String, ByVal IndexPage As Boolean) As searchResults
            Dim results() As Object = Me.Invoke("fetchSearchResults", New Object() {UniqueKey, IndexPage})
            Return CType(results(0),searchResults)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fetchSearchResultsAsync(ByVal UniqueKey As String, ByVal IndexPage As Boolean)
            Me.fetchSearchResultsAsync(UniqueKey, IndexPage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fetchSearchResultsAsync(ByVal UniqueKey As String, ByVal IndexPage As Boolean, ByVal userState As Object)
            If (Me.fetchSearchResultsOperationCompleted Is Nothing) Then
                Me.fetchSearchResultsOperationCompleted = AddressOf Me.OnfetchSearchResultsOperationCompleted
            End If
            Me.InvokeAsync("fetchSearchResults", New Object() {UniqueKey, IndexPage}, Me.fetchSearchResultsOperationCompleted, userState)
        End Sub
        
        Private Sub OnfetchSearchResultsOperationCompleted(ByVal arg As Object)
            If (Not (Me.fetchSearchResultsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fetchSearchResultsCompleted(Me, New fetchSearchResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/SearchEngine/saveSearchQuery", RequestNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", ResponseNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function saveSearchQuery( _
                    ByVal partnerID As Integer,  _
                    ByVal partnerKey As Integer,  _
                    ByVal searchType As Integer,  _
                    ByVal catRef As Integer,  _
                    ByVal startDate As Date,  _
                    ByVal numNights As Integer,  _
                    ByVal dateFlex As Integer,  _
                    ByVal minSleeps As Integer,  _
                    ByVal minPrice As Integer,  _
                    ByVal maxPrice As Integer,  _
                    ByVal keywordText As String,  _
                    ByVal propType As Integer,  _
                    ByVal filter1 As Boolean,  _
                    ByVal filter2 As Boolean,  _
                    ByVal filter3 As Boolean,  _
                    ByVal filter4 As Boolean,  _
                    ByVal filter5 As Boolean) As searchKey
            Dim results() As Object = Me.Invoke("saveSearchQuery", New Object() {partnerID, partnerKey, searchType, catRef, startDate, numNights, dateFlex, minSleeps, minPrice, maxPrice, keywordText, propType, filter1, filter2, filter3, filter4, filter5})
            Return CType(results(0),searchKey)
        End Function
        
        '''<remarks/>
        Public Overloads Sub saveSearchQueryAsync( _
                    ByVal partnerID As Integer,  _
                    ByVal partnerKey As Integer,  _
                    ByVal searchType As Integer,  _
                    ByVal catRef As Integer,  _
                    ByVal startDate As Date,  _
                    ByVal numNights As Integer,  _
                    ByVal dateFlex As Integer,  _
                    ByVal minSleeps As Integer,  _
                    ByVal minPrice As Integer,  _
                    ByVal maxPrice As Integer,  _
                    ByVal keywordText As String,  _
                    ByVal propType As Integer,  _
                    ByVal filter1 As Boolean,  _
                    ByVal filter2 As Boolean,  _
                    ByVal filter3 As Boolean,  _
                    ByVal filter4 As Boolean,  _
                    ByVal filter5 As Boolean)
            Me.saveSearchQueryAsync(partnerID, partnerKey, searchType, catRef, startDate, numNights, dateFlex, minSleeps, minPrice, maxPrice, keywordText, propType, filter1, filter2, filter3, filter4, filter5, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub saveSearchQueryAsync( _
                    ByVal partnerID As Integer,  _
                    ByVal partnerKey As Integer,  _
                    ByVal searchType As Integer,  _
                    ByVal catRef As Integer,  _
                    ByVal startDate As Date,  _
                    ByVal numNights As Integer,  _
                    ByVal dateFlex As Integer,  _
                    ByVal minSleeps As Integer,  _
                    ByVal minPrice As Integer,  _
                    ByVal maxPrice As Integer,  _
                    ByVal keywordText As String,  _
                    ByVal propType As Integer,  _
                    ByVal filter1 As Boolean,  _
                    ByVal filter2 As Boolean,  _
                    ByVal filter3 As Boolean,  _
                    ByVal filter4 As Boolean,  _
                    ByVal filter5 As Boolean,  _
                    ByVal userState As Object)
            If (Me.saveSearchQueryOperationCompleted Is Nothing) Then
                Me.saveSearchQueryOperationCompleted = AddressOf Me.OnsaveSearchQueryOperationCompleted
            End If
            Me.InvokeAsync("saveSearchQuery", New Object() {partnerID, partnerKey, searchType, catRef, startDate, numNights, dateFlex, minSleeps, minPrice, maxPrice, keywordText, propType, filter1, filter2, filter3, filter4, filter5}, Me.saveSearchQueryOperationCompleted, userState)
        End Sub
        
        Private Sub OnsaveSearchQueryOperationCompleted(ByVal arg As Object)
            If (Not (Me.saveSearchQueryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent saveSearchQueryCompleted(Me, New saveSearchQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/SearchEngine/fetchPropertyData", RequestNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", ResponseNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fetchPropertyData(ByVal searchType As Integer, ByVal propRef As Integer) As propertyData
            Dim results() As Object = Me.Invoke("fetchPropertyData", New Object() {searchType, propRef})
            Return CType(results(0),propertyData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fetchPropertyDataAsync(ByVal searchType As Integer, ByVal propRef As Integer)
            Me.fetchPropertyDataAsync(searchType, propRef, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fetchPropertyDataAsync(ByVal searchType As Integer, ByVal propRef As Integer, ByVal userState As Object)
            If (Me.fetchPropertyDataOperationCompleted Is Nothing) Then
                Me.fetchPropertyDataOperationCompleted = AddressOf Me.OnfetchPropertyDataOperationCompleted
            End If
            Me.InvokeAsync("fetchPropertyData", New Object() {searchType, propRef}, Me.fetchPropertyDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnfetchPropertyDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.fetchPropertyDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fetchPropertyDataCompleted(Me, New fetchPropertyDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/SearchEngine/fetchLocationData", RequestNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", ResponseNamespace:="http://tempuri.org/VillarentersWebService/SearchEngine", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fetchLocationData(ByVal catRef As Integer) As locationData
            Dim results() As Object = Me.Invoke("fetchLocationData", New Object() {catRef})
            Return CType(results(0),locationData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fetchLocationDataAsync(ByVal catRef As Integer)
            Me.fetchLocationDataAsync(catRef, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fetchLocationDataAsync(ByVal catRef As Integer, ByVal userState As Object)
            If (Me.fetchLocationDataOperationCompleted Is Nothing) Then
                Me.fetchLocationDataOperationCompleted = AddressOf Me.OnfetchLocationDataOperationCompleted
            End If
            Me.InvokeAsync("fetchLocationData", New Object() {catRef}, Me.fetchLocationDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnfetchLocationDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.fetchLocationDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fetchLocationDataCompleted(Me, New fetchLocationDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class childLocations
        
        Private errorCodeField As Integer
        
        Private childLocations1Field() As childLocation
        
        '''<remarks/>
        Public Property errorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute("childLocations"),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property childLocations1() As childLocation()
            Get
                Return Me.childLocations1Field
            End Get
            Set
                Me.childLocations1Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class childLocation
        
        Private catRefField As Integer
        
        Private catNameField As String
        
        Private propCountField As Integer
        
        '''<remarks/>
        Public Property catRef() As Integer
            Get
                Return Me.catRefField
            End Get
            Set
                Me.catRefField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property catName() As String
            Get
                Return Me.catNameField
            End Get
            Set
                Me.catNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propCount() As Integer
            Get
                Return Me.propCountField
            End Get
            Set
                Me.propCountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class locationPath
        
        Private catRefField As Integer
        
        Private locationNameField As String
        
        Private locationPropertiesField As String
        
        Private locationGuideField As String
        
        '''<remarks/>
        Public Property catRef() As Integer
            Get
                Return Me.catRefField
            End Get
            Set
                Me.catRefField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property locationName() As String
            Get
                Return Me.locationNameField
            End Get
            Set
                Me.locationNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property locationProperties() As String
            Get
                Return Me.locationPropertiesField
            End Get
            Set
                Me.locationPropertiesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property locationGuide() As String
            Get
                Return Me.locationGuideField
            End Get
            Set
                Me.locationGuideField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class locationData
        
        Private locationNameField As String
        
        Private rentalCountField As Integer
        
        Private saleCountField As Integer
        
        Private bbCountField As Integer
        
        Private hotelCountField As Integer
        
        Private locationPathField() As locationPath
        
        '''<remarks/>
        Public Property locationName() As String
            Get
                Return Me.locationNameField
            End Get
            Set
                Me.locationNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rentalCount() As Integer
            Get
                Return Me.rentalCountField
            End Get
            Set
                Me.rentalCountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property saleCount() As Integer
            Get
                Return Me.saleCountField
            End Get
            Set
                Me.saleCountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bbCount() As Integer
            Get
                Return Me.bbCountField
            End Get
            Set
                Me.bbCountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property hotelCount() As Integer
            Get
                Return Me.hotelCountField
            End Get
            Set
                Me.hotelCountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property locationPath() As locationPath()
            Get
                Return Me.locationPathField
            End Get
            Set
                Me.locationPathField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class propertyData
        
        Private propTitleField As String
        
        Private propLinkField As String
        
        Private propImageField As String
        
        Private propSummaryField As String
        
        Private propTownField As String
        
        Private propCountryField As String
        
        Private propStyleField As String
        
        Private propAccomField As String
        
        Private minPriceField As Decimal
        
        Private propCurrencyField As String
        
        Private propSleepsField As Integer
        
        Private propInstantField As Boolean
        
        Private propStarsField As Integer
        
        Private userRatingField As Integer
        
        Private propLonField As Decimal
        
        Private propLatField As Decimal
        
        Private errorMsgField As String
        
        '''<remarks/>
        Public Property propTitle() As String
            Get
                Return Me.propTitleField
            End Get
            Set
                Me.propTitleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propLink() As String
            Get
                Return Me.propLinkField
            End Get
            Set
                Me.propLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propImage() As String
            Get
                Return Me.propImageField
            End Get
            Set
                Me.propImageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propSummary() As String
            Get
                Return Me.propSummaryField
            End Get
            Set
                Me.propSummaryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propTown() As String
            Get
                Return Me.propTownField
            End Get
            Set
                Me.propTownField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propCountry() As String
            Get
                Return Me.propCountryField
            End Get
            Set
                Me.propCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propStyle() As String
            Get
                Return Me.propStyleField
            End Get
            Set
                Me.propStyleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propAccom() As String
            Get
                Return Me.propAccomField
            End Get
            Set
                Me.propAccomField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property minPrice() As Decimal
            Get
                Return Me.minPriceField
            End Get
            Set
                Me.minPriceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propCurrency() As String
            Get
                Return Me.propCurrencyField
            End Get
            Set
                Me.propCurrencyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propSleeps() As Integer
            Get
                Return Me.propSleepsField
            End Get
            Set
                Me.propSleepsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propInstant() As Boolean
            Get
                Return Me.propInstantField
            End Get
            Set
                Me.propInstantField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propStars() As Integer
            Get
                Return Me.propStarsField
            End Get
            Set
                Me.propStarsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property userRating() As Integer
            Get
                Return Me.userRatingField
            End Get
            Set
                Me.userRatingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propLon() As Decimal
            Get
                Return Me.propLonField
            End Get
            Set
                Me.propLonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property propLat() As Decimal
            Get
                Return Me.propLatField
            End Get
            Set
                Me.propLatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property errorMsg() As String
            Get
                Return Me.errorMsgField
            End Get
            Set
                Me.errorMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class searchKey
        
        Private uniqueKeyField As System.Guid
        
        Private errorCodeField As String
        
        '''<remarks/>
        Public Property UniqueKey() As System.Guid
            Get
                Return Me.uniqueKeyField
            End Get
            Set
                Me.uniqueKeyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property errorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class resultProperty
        
        Private propRefField As Integer
        
        '''<remarks/>
        Public Property propRef() As Integer
            Get
                Return Me.propRefField
            End Get
            Set
                Me.propRefField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class searchResults
        
        Private errorCodeField As Integer
        
        Private searchResults1Field() As resultProperty
        
        '''<remarks/>
        Public Property errorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute("searchResults"),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property searchResults1() As resultProperty()
            Get
                Return Me.searchResults1Field
            End Get
            Set
                Me.searchResults1Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class selectedLocations
        
        Private catRefField As Integer
        
        '''<remarks/>
        Public Property catRef() As Integer
            Get
                Return Me.catRefField
            End Get
            Set
                Me.catRefField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/SearchEngine")>  _
    Partial Public Class searchCriteria
        
        Private keywordsField As String
        
        Private startDateField As Date
        
        Private nightsField As Integer
        
        Private partySizeField As Integer
        
        Private giveTakeField As Integer
        
        Private catRefField As Integer
        
        Private errorCodeField As Integer
        
        Private selectedLocationsField() As selectedLocations
        
        '''<remarks/>
        Public Property Keywords() As String
            Get
                Return Me.keywordsField
            End Get
            Set
                Me.keywordsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nights() As Integer
            Get
                Return Me.nightsField
            End Get
            Set
                Me.nightsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PartySize() As Integer
            Get
                Return Me.partySizeField
            End Get
            Set
                Me.partySizeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GiveTake() As Integer
            Get
                Return Me.giveTakeField
            End Get
            Set
                Me.giveTakeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CatRef() As Integer
            Get
                Return Me.catRefField
            End Get
            Set
                Me.catRefField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property errorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property selectedLocations() As selectedLocations()
            Get
                Return Me.selectedLocationsField
            End Get
            Set
                Me.selectedLocationsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub fetchNextLocationsCompletedEventHandler(ByVal sender As Object, ByVal e As fetchNextLocationsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fetchNextLocationsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As childLocations
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),childLocations)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub fetchSearchCriteriaCompletedEventHandler(ByVal sender As Object, ByVal e As fetchSearchCriteriaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fetchSearchCriteriaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As searchCriteria
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),searchCriteria)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub fetchSearchResultsCompletedEventHandler(ByVal sender As Object, ByVal e As fetchSearchResultsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fetchSearchResultsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As searchResults
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),searchResults)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub saveSearchQueryCompletedEventHandler(ByVal sender As Object, ByVal e As saveSearchQueryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class saveSearchQueryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As searchKey
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),searchKey)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub fetchPropertyDataCompletedEventHandler(ByVal sender As Object, ByVal e As fetchPropertyDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fetchPropertyDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As propertyData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),propertyData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub fetchLocationDataCompletedEventHandler(ByVal sender As Object, ByVal e As fetchLocationDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fetchLocationDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As locationData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),locationData)
            End Get
        End Property
    End Class
End Namespace
