'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4200.
'
Namespace VR_pagedatafeed
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="pageDataFeedSoap", [Namespace]:="http://tempuri.org/VillarentersWebService/pageDataFeed")>  _
    Partial Public Class pageDataFeed
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private fetchHeaderDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fetchLinkDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fetchLinkSectionDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.internalWebServices.My.MySettings.Default.internalWebServices_VR_pagedatafeed_pageDataFeed
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event fetchHeaderDataCompleted As fetchHeaderDataCompletedEventHandler
        
        '''<remarks/>
        Public Event fetchLinkDataCompleted As fetchLinkDataCompletedEventHandler
        
        '''<remarks/>
        Public Event fetchLinkSectionDataCompleted As fetchLinkSectionDataCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/pageDataFeed/fetchHeaderData", RequestNamespace:="http://tempuri.org/VillarentersWebService/pageDataFeed", ResponseNamespace:="http://tempuri.org/VillarentersWebService/pageDataFeed", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fetchHeaderData(ByVal pageID As Integer) As headerData
            Dim results() As Object = Me.Invoke("fetchHeaderData", New Object() {pageID})
            Return CType(results(0),headerData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fetchHeaderDataAsync(ByVal pageID As Integer)
            Me.fetchHeaderDataAsync(pageID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fetchHeaderDataAsync(ByVal pageID As Integer, ByVal userState As Object)
            If (Me.fetchHeaderDataOperationCompleted Is Nothing) Then
                Me.fetchHeaderDataOperationCompleted = AddressOf Me.OnfetchHeaderDataOperationCompleted
            End If
            Me.InvokeAsync("fetchHeaderData", New Object() {pageID}, Me.fetchHeaderDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnfetchHeaderDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.fetchHeaderDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fetchHeaderDataCompleted(Me, New fetchHeaderDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/pageDataFeed/fetchLinkData", RequestNamespace:="http://tempuri.org/VillarentersWebService/pageDataFeed", ResponseNamespace:="http://tempuri.org/VillarentersWebService/pageDataFeed", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fetchLinkData(ByVal pageID As Integer, ByVal LinkRight As Boolean) As navigationRows
            Dim results() As Object = Me.Invoke("fetchLinkData", New Object() {pageID, LinkRight})
            Return CType(results(0),navigationRows)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fetchLinkDataAsync(ByVal pageID As Integer, ByVal LinkRight As Boolean)
            Me.fetchLinkDataAsync(pageID, LinkRight, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fetchLinkDataAsync(ByVal pageID As Integer, ByVal LinkRight As Boolean, ByVal userState As Object)
            If (Me.fetchLinkDataOperationCompleted Is Nothing) Then
                Me.fetchLinkDataOperationCompleted = AddressOf Me.OnfetchLinkDataOperationCompleted
            End If
            Me.InvokeAsync("fetchLinkData", New Object() {pageID, LinkRight}, Me.fetchLinkDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnfetchLinkDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.fetchLinkDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fetchLinkDataCompleted(Me, New fetchLinkDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/pageDataFeed/fetchLinkSectionData", RequestNamespace:="http://tempuri.org/VillarentersWebService/pageDataFeed", ResponseNamespace:="http://tempuri.org/VillarentersWebService/pageDataFeed", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fetchLinkSectionData(ByVal pageID As Integer, ByVal sectionID As Integer) As navigationRows
            Dim results() As Object = Me.Invoke("fetchLinkSectionData", New Object() {pageID, sectionID})
            Return CType(results(0),navigationRows)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fetchLinkSectionDataAsync(ByVal pageID As Integer, ByVal sectionID As Integer)
            Me.fetchLinkSectionDataAsync(pageID, sectionID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fetchLinkSectionDataAsync(ByVal pageID As Integer, ByVal sectionID As Integer, ByVal userState As Object)
            If (Me.fetchLinkSectionDataOperationCompleted Is Nothing) Then
                Me.fetchLinkSectionDataOperationCompleted = AddressOf Me.OnfetchLinkSectionDataOperationCompleted
            End If
            Me.InvokeAsync("fetchLinkSectionData", New Object() {pageID, sectionID}, Me.fetchLinkSectionDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnfetchLinkSectionDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.fetchLinkSectionDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fetchLinkSectionDataCompleted(Me, New fetchLinkSectionDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/pageDataFeed")>  _
    Partial Public Class headerData
        
        Private pageTitleField As String
        
        Private pageDescField As String
        
        Private pageKeywordsField As String
        
        Private pageBodyField As String
        
        Private errorMsgField As String
        
        '''<remarks/>
        Public Property pageTitle() As String
            Get
                Return Me.pageTitleField
            End Get
            Set
                Me.pageTitleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pageDesc() As String
            Get
                Return Me.pageDescField
            End Get
            Set
                Me.pageDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pageKeywords() As String
            Get
                Return Me.pageKeywordsField
            End Get
            Set
                Me.pageKeywordsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pageBody() As String
            Get
                Return Me.pageBodyField
            End Get
            Set
                Me.pageBodyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property errorMsg() As String
            Get
                Return Me.errorMsgField
            End Get
            Set
                Me.errorMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/pageDataFeed")>  _
    Partial Public Class navigationItem
        
        Private linkUrlField As String
        
        Private linkNameField As String
        
        '''<remarks/>
        Public Property linkUrl() As String
            Get
                Return Me.linkUrlField
            End Get
            Set
                Me.linkUrlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property linkName() As String
            Get
                Return Me.linkNameField
            End Get
            Set
                Me.linkNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/pageDataFeed")>  _
    Partial Public Class navigationRows
        
        Private navigationRows1Field() As navigationItem
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute("navigationRows"),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property navigationRows1() As navigationItem()
            Get
                Return Me.navigationRows1Field
            End Get
            Set
                Me.navigationRows1Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub fetchHeaderDataCompletedEventHandler(ByVal sender As Object, ByVal e As fetchHeaderDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fetchHeaderDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As headerData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),headerData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub fetchLinkDataCompletedEventHandler(ByVal sender As Object, ByVal e As fetchLinkDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fetchLinkDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As navigationRows
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),navigationRows)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub fetchLinkSectionDataCompletedEventHandler(ByVal sender As Object, ByVal e As fetchLinkSectionDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fetchLinkSectionDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As navigationRows
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),navigationRows)
            End Get
        End Property
    End Class
End Namespace
