'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4200.
'
Namespace VR_VillaSearch
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="villa_searchSoap", [Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class villa_search
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GoogleMapsLocatorsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private VillaSearchOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPropertyAvailabilityOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPropertyReviewsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetChildLocationsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCountryListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private VillaSearchV2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.internalWebServices.My.MySettings.Default.internalWebServices_VR_VillaSearch_villa_search
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GoogleMapsLocatorsCompleted As GoogleMapsLocatorsCompletedEventHandler
        
        '''<remarks/>
        Public Event VillaSearchCompleted As VillaSearchCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPropertyAvailabilityCompleted As GetPropertyAvailabilityCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPropertyReviewsCompleted As GetPropertyReviewsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetChildLocationsCompleted As GetChildLocationsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCountryListCompleted As GetCountryListCompletedEventHandler
        
        '''<remarks/>
        Public Event VillaSearchV2Completed As VillaSearchV2CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/villa_search/GoogleMapsLocators", RequestNamespace:="http://tempuri.org/VillarentersWebService/villa_search", ResponseNamespace:="http://tempuri.org/VillarentersWebService/villa_search", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GoogleMapsLocators( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal intPropType As Integer,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer,  _
                    ByVal VRF As String) As <System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://www.cpandl.com", IsNullable:=false)> marker()
            Dim results() As Object = Me.Invoke("GoogleMapsLocators", New Object() {Rag, strOwnerRefs, strPropRefs, intPropType, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder, VRF})
            Return CType(results(0),marker())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GoogleMapsLocatorsAsync( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal intPropType As Integer,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer,  _
                    ByVal VRF As String)
            Me.GoogleMapsLocatorsAsync(Rag, strOwnerRefs, strPropRefs, intPropType, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder, VRF, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GoogleMapsLocatorsAsync( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal intPropType As Integer,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer,  _
                    ByVal VRF As String,  _
                    ByVal userState As Object)
            If (Me.GoogleMapsLocatorsOperationCompleted Is Nothing) Then
                Me.GoogleMapsLocatorsOperationCompleted = AddressOf Me.OnGoogleMapsLocatorsOperationCompleted
            End If
            Me.InvokeAsync("GoogleMapsLocators", New Object() {Rag, strOwnerRefs, strPropRefs, intPropType, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder, VRF}, Me.GoogleMapsLocatorsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGoogleMapsLocatorsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GoogleMapsLocatorsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GoogleMapsLocatorsCompleted(Me, New GoogleMapsLocatorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/villa_search/VillaSearch", RequestNamespace:="http://tempuri.org/VillarentersWebService/villa_search", ResponseNamespace:="http://tempuri.org/VillarentersWebService/villa_search", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VillaSearch( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer) As VillaResults
            Dim results() As Object = Me.Invoke("VillaSearch", New Object() {Rag, strOwnerRefs, strPropRefs, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder})
            Return CType(results(0),VillaResults)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VillaSearchAsync( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer)
            Me.VillaSearchAsync(Rag, strOwnerRefs, strPropRefs, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VillaSearchAsync( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer,  _
                    ByVal userState As Object)
            If (Me.VillaSearchOperationCompleted Is Nothing) Then
                Me.VillaSearchOperationCompleted = AddressOf Me.OnVillaSearchOperationCompleted
            End If
            Me.InvokeAsync("VillaSearch", New Object() {Rag, strOwnerRefs, strPropRefs, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder}, Me.VillaSearchOperationCompleted, userState)
        End Sub
        
        Private Sub OnVillaSearchOperationCompleted(ByVal arg As Object)
            If (Not (Me.VillaSearchCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VillaSearchCompleted(Me, New VillaSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/villa_search/GetPropertyAvailability", RequestNamespace:="http://tempuri.org/VillarentersWebService/villa_search", ResponseNamespace:="http://tempuri.org/VillarentersWebService/villa_search", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPropertyAvailability(ByVal prop_ref As String, ByVal VRF As String) As Availability
            Dim results() As Object = Me.Invoke("GetPropertyAvailability", New Object() {prop_ref, VRF})
            Return CType(results(0),Availability)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPropertyAvailabilityAsync(ByVal prop_ref As String, ByVal VRF As String)
            Me.GetPropertyAvailabilityAsync(prop_ref, VRF, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPropertyAvailabilityAsync(ByVal prop_ref As String, ByVal VRF As String, ByVal userState As Object)
            If (Me.GetPropertyAvailabilityOperationCompleted Is Nothing) Then
                Me.GetPropertyAvailabilityOperationCompleted = AddressOf Me.OnGetPropertyAvailabilityOperationCompleted
            End If
            Me.InvokeAsync("GetPropertyAvailability", New Object() {prop_ref, VRF}, Me.GetPropertyAvailabilityOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPropertyAvailabilityOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPropertyAvailabilityCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPropertyAvailabilityCompleted(Me, New GetPropertyAvailabilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/villa_search/GetPropertyReviews", RequestNamespace:="http://tempuri.org/VillarentersWebService/villa_search", ResponseNamespace:="http://tempuri.org/VillarentersWebService/villa_search", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPropertyReviews(ByVal prop_ref As String, ByVal VRF As String) As PropertyReview
            Dim results() As Object = Me.Invoke("GetPropertyReviews", New Object() {prop_ref, VRF})
            Return CType(results(0),PropertyReview)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPropertyReviewsAsync(ByVal prop_ref As String, ByVal VRF As String)
            Me.GetPropertyReviewsAsync(prop_ref, VRF, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPropertyReviewsAsync(ByVal prop_ref As String, ByVal VRF As String, ByVal userState As Object)
            If (Me.GetPropertyReviewsOperationCompleted Is Nothing) Then
                Me.GetPropertyReviewsOperationCompleted = AddressOf Me.OnGetPropertyReviewsOperationCompleted
            End If
            Me.InvokeAsync("GetPropertyReviews", New Object() {prop_ref, VRF}, Me.GetPropertyReviewsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPropertyReviewsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPropertyReviewsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPropertyReviewsCompleted(Me, New GetPropertyReviewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/villa_search/GetChildLocations", RequestNamespace:="http://tempuri.org/VillarentersWebService/villa_search", ResponseNamespace:="http://tempuri.org/VillarentersWebService/villa_search", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetChildLocations(ByVal ParentID As String, ByVal VRF As String) As ChildLocation
            Dim results() As Object = Me.Invoke("GetChildLocations", New Object() {ParentID, VRF})
            Return CType(results(0),ChildLocation)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetChildLocationsAsync(ByVal ParentID As String, ByVal VRF As String)
            Me.GetChildLocationsAsync(ParentID, VRF, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetChildLocationsAsync(ByVal ParentID As String, ByVal VRF As String, ByVal userState As Object)
            If (Me.GetChildLocationsOperationCompleted Is Nothing) Then
                Me.GetChildLocationsOperationCompleted = AddressOf Me.OnGetChildLocationsOperationCompleted
            End If
            Me.InvokeAsync("GetChildLocations", New Object() {ParentID, VRF}, Me.GetChildLocationsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetChildLocationsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetChildLocationsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetChildLocationsCompleted(Me, New GetChildLocationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/villa_search/GetCountryList", RequestNamespace:="http://tempuri.org/VillarentersWebService/villa_search", ResponseNamespace:="http://tempuri.org/VillarentersWebService/villa_search", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCountryList(ByVal country_ref As String, ByVal VRF As String) As CountryList
            Dim results() As Object = Me.Invoke("GetCountryList", New Object() {country_ref, VRF})
            Return CType(results(0),CountryList)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCountryListAsync(ByVal country_ref As String, ByVal VRF As String)
            Me.GetCountryListAsync(country_ref, VRF, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCountryListAsync(ByVal country_ref As String, ByVal VRF As String, ByVal userState As Object)
            If (Me.GetCountryListOperationCompleted Is Nothing) Then
                Me.GetCountryListOperationCompleted = AddressOf Me.OnGetCountryListOperationCompleted
            End If
            Me.InvokeAsync("GetCountryList", New Object() {country_ref, VRF}, Me.GetCountryListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCountryListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCountryListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCountryListCompleted(Me, New GetCountryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillarentersWebService/villa_search/VillaSearchV2", RequestNamespace:="http://tempuri.org/VillarentersWebService/villa_search", ResponseNamespace:="http://tempuri.org/VillarentersWebService/villa_search", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VillaSearchV2( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal intPropType As Integer,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer,  _
                    ByVal VRF As String) As VillaResults
            Dim results() As Object = Me.Invoke("VillaSearchV2", New Object() {Rag, strOwnerRefs, strPropRefs, intPropType, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder, VRF})
            Return CType(results(0),VillaResults)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VillaSearchV2Async( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal intPropType As Integer,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer,  _
                    ByVal VRF As String)
            Me.VillaSearchV2Async(Rag, strOwnerRefs, strPropRefs, intPropType, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder, VRF, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VillaSearchV2Async( _
                    ByVal Rag As String,  _
                    ByVal strOwnerRefs As String,  _
                    ByVal strPropRefs As String,  _
                    ByVal intPropType As Integer,  _
                    ByVal strLocationRefs As String,  _
                    ByVal intMaxPrice As Integer,  _
                    ByVal intMinPrice As Integer,  _
                    ByVal intSleeps As Integer,  _
                    ByVal blnInstantBooking As Boolean,  _
                    ByVal intVillarentersIndex As Integer,  _
                    ByVal intDiscountType As Integer,  _
                    ByVal intBranding As Integer,  _
                    ByVal intPage As Integer,  _
                    ByVal intItemsPerPage As Integer,  _
                    ByVal blnEnableAvailabilitySearch As Boolean,  _
                    ByVal strFromYYYYMMDD As String,  _
                    ByVal strToYYYYMMDD As String,  _
                    ByVal intSortOrder As Integer,  _
                    ByVal VRF As String,  _
                    ByVal userState As Object)
            If (Me.VillaSearchV2OperationCompleted Is Nothing) Then
                Me.VillaSearchV2OperationCompleted = AddressOf Me.OnVillaSearchV2OperationCompleted
            End If
            Me.InvokeAsync("VillaSearchV2", New Object() {Rag, strOwnerRefs, strPropRefs, intPropType, strLocationRefs, intMaxPrice, intMinPrice, intSleeps, blnInstantBooking, intVillarentersIndex, intDiscountType, intBranding, intPage, intItemsPerPage, blnEnableAvailabilitySearch, strFromYYYYMMDD, strToYYYYMMDD, intSortOrder, VRF}, Me.VillaSearchV2OperationCompleted, userState)
        End Sub
        
        Private Sub OnVillaSearchV2OperationCompleted(ByVal arg As Object)
            If (Not (Me.VillaSearchV2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VillaSearchV2Completed(Me, New VillaSearchV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.cpandl.com")>  _
    Partial Public Class marker
        
        Private latField As String
        
        Private lngField As String
        
        Private htmlField As String
        
        Private labelField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property lat() As String
            Get
                Return Me.latField
            End Get
            Set
                Me.latField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property lng() As String
            Get
                Return Me.lngField
            End Get
            Set
                Me.lngField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property html() As String
            Get
                Return Me.htmlField
            End Get
            Set
                Me.htmlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property label() As String
            Get
                Return Me.labelField
            End Get
            Set
                Me.labelField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class SubRegion
        
        Private descriptionField As String
        
        Private idField As Integer
        
        Private parentIDField As Integer
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParentID() As Integer
            Get
                Return Me.parentIDField
            End Get
            Set
                Me.parentIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class Region
        
        Private descriptionField As String
        
        Private idField As Integer
        
        Private parentIDField As Integer
        
        Private subRegionsField() As SubRegion
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParentID() As Integer
            Get
                Return Me.parentIDField
            End Get
            Set
                Me.parentIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property SubRegions() As SubRegion()
            Get
                Return Me.subRegionsField
            End Get
            Set
                Me.subRegionsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class Country
        
        Private descriptionField As String
        
        Private idField As Integer
        
        Private regionsField() As Region
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Regions() As Region()
            Get
                Return Me.regionsField
            End Get
            Set
                Me.regionsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class CountryList
        
        Private countryRefField As Integer
        
        Private countriesField() As Country
        
        '''<remarks/>
        Public Property CountryRef() As Integer
            Get
                Return Me.countryRefField
            End Get
            Set
                Me.countryRefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Countries() As Country()
            Get
                Return Me.countriesField
            End Get
            Set
                Me.countriesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class ChildLocation
        
        Private requestedParentIDField As Integer
        
        Private vRFField As String
        
        Private childLocationsField() As Location
        
        '''<remarks/>
        Public Property RequestedParentID() As Integer
            Get
                Return Me.requestedParentIDField
            End Get
            Set
                Me.requestedParentIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VRF() As String
            Get
                Return Me.vRFField
            End Get
            Set
                Me.vRFField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property ChildLocations() As Location()
            Get
                Return Me.childLocationsField
            End Get
            Set
                Me.childLocationsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class Location
        
        Private locationRefField As Long
        
        Private locationDescriptionField As String
        
        Private parentIDField As Integer
        
        '''<remarks/>
        Public Property LocationRef() As Long
            Get
                Return Me.locationRefField
            End Get
            Set
                Me.locationRefField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LocationDescription() As String
            Get
                Return Me.locationDescriptionField
            End Get
            Set
                Me.locationDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParentID() As Integer
            Get
                Return Me.parentIDField
            End Get
            Set
                Me.parentIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class Review
        
        Private reviewDateField As String
        
        Private starRatingField As Integer
        
        Private byField As String
        
        Private fromField As String
        
        Private articleField As String
        
        '''<remarks/>
        Public Property ReviewDate() As String
            Get
                Return Me.reviewDateField
            End Get
            Set
                Me.reviewDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StarRating() As Integer
            Get
                Return Me.starRatingField
            End Get
            Set
                Me.starRatingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property By() As String
            Get
                Return Me.byField
            End Get
            Set
                Me.byField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property From() As String
            Get
                Return Me.fromField
            End Get
            Set
                Me.fromField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Article() As String
            Get
                Return Me.articleField
            End Get
            Set
                Me.articleField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class PropertyReview
        
        Private prop_refField As Long
        
        Private reviewsField() As Review
        
        '''<remarks/>
        Public Property prop_ref() As Long
            Get
                Return Me.prop_refField
            End Get
            Set
                Me.prop_refField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Reviews() As Review()
            Get
                Return Me.reviewsField
            End Get
            Set
                Me.reviewsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class PropertyAvailability
        
        Private intYearField As Integer
        
        Private intMonthField As Integer
        
        Private monthAvailabilityField As String
        
        Private monthPricingField As String
        
        '''<remarks/>
        Public Property intYear() As Integer
            Get
                Return Me.intYearField
            End Get
            Set
                Me.intYearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property intMonth() As Integer
            Get
                Return Me.intMonthField
            End Get
            Set
                Me.intMonthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MonthAvailability() As String
            Get
                Return Me.monthAvailabilityField
            End Get
            Set
                Me.monthAvailabilityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MonthPricing() As String
            Get
                Return Me.monthPricingField
            End Get
            Set
                Me.monthPricingField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class Availability
        
        Private prop_refField As Long
        
        Private currencyField As String
        
        Private minNoticeField As Integer
        
        Private minBookingPeriodField As Integer
        
        Private propertyAvailabilitiesField() As PropertyAvailability
        
        '''<remarks/>
        Public Property prop_ref() As Long
            Get
                Return Me.prop_refField
            End Get
            Set
                Me.prop_refField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property currency() As String
            Get
                Return Me.currencyField
            End Get
            Set
                Me.currencyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property minNotice() As Integer
            Get
                Return Me.minNoticeField
            End Get
            Set
                Me.minNoticeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property minBookingPeriod() As Integer
            Get
                Return Me.minBookingPeriodField
            End Get
            Set
                Me.minBookingPeriodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property PropertyAvailabilities() As PropertyAvailability()
            Get
                Return Me.propertyAvailabilitiesField
            End Get
            Set
                Me.propertyAvailabilitiesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class UserField
        
        Private userLocationField As String
        
        Private userDistanceField As String
        
        '''<remarks/>
        Public Property UserLocation() As String
            Get
                Return Me.userLocationField
            End Get
            Set
                Me.userLocationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserDistance() As String
            Get
                Return Me.userDistanceField
            End Get
            Set
                Me.userDistanceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class PropImage
        
        Private imageCaptionField As String
        
        Private imageURLField As String
        
        '''<remarks/>
        Public Property ImageCaption() As String
            Get
                Return Me.imageCaptionField
            End Get
            Set
                Me.imageCaptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImageURL() As String
            Get
                Return Me.imageURLField
            End Get
            Set
                Me.imageURLField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class Description
        
        Private titleField As String
        
        Private paragraphField As String
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Paragraph() As String
            Get
                Return Me.paragraphField
            End Get
            Set
                Me.paragraphField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class Villa
        
        Private prop_refField As Long
        
        Private owner_refField As Long
        
        Private propTypeField As String
        
        Private titleField As String
        
        Private summaryField As String
        
        Private descriptionsField() As Description
        
        Private propImagesField() As PropImage
        
        Private filenameField As String
        
        Private locationsField() As Location
        
        Private minPriceField As Decimal
        
        Private maxPriceField As Decimal
        
        Private currencyField As String
        
        Private sleepsField As Integer
        
        Private doubleBedsField As Integer
        
        Private twinBedsField As Integer
        
        Private singleBedsField As Integer
        
        Private cotsField As Integer
        
        Private bathroomsField As Integer
        
        Private tvField As Boolean
        
        Private satelliteField As Boolean
        
        Private telephoneField As Boolean
        
        Private cookerField As Boolean
        
        Private microwaveField As Boolean
        
        Private fridgeField As Boolean
        
        Private freezerField As Boolean
        
        Private internetField As Boolean
        
        Private centralHeatingField As Boolean
        
        Private linenProvidedField As Boolean
        
        Private airConditioningField As Boolean
        
        Private trafficField As String
        
        Private seasideField As Boolean
        
        Private sightSeeingField As Boolean
        
        Private touristField As Boolean
        
        Private romanticField As Boolean
        
        Private relaxingField As Boolean
        
        Private activityField As Boolean
        
        Private petsField As Boolean
        
        Private openFireField As Boolean
        
        Private gardenField As Boolean
        
        Private patioField As Boolean
        
        Private balconyField As Boolean
        
        Private privatePoolField As Boolean
        
        Private sharedPoolField As Boolean
        
        Private tennisCourtField As Boolean
        
        Private parkingField As Boolean
        
        Private airportField As String
        
        Private airportDistanceField As String
        
        Private userFieldsField() As UserField
        
        Private mapLinkField As String
        
        Private lonField As Double
        
        Private latField As Double
        
        Private extraField As String
        
        Private beachField As String
        
        Private sailingField As String
        
        Private swimmingField As String
        
        Private walkingField As String
        
        Private cyclingField As String
        
        Private horseRidingField As String
        
        Private skiingField As String
        
        Private golfField As String
        
        Private tennisField As String
        
        Private climbingField As String
        
        Private nonesmokingField As Boolean
        
        Private instantBookingField As Boolean
        
        Private villarentersIndexField As Integer
        
        Private externalRefField As String
        
        '''<remarks/>
        Public Property prop_ref() As Long
            Get
                Return Me.prop_refField
            End Get
            Set
                Me.prop_refField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property owner_ref() As Long
            Get
                Return Me.owner_refField
            End Get
            Set
                Me.owner_refField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PropType() As String
            Get
                Return Me.propTypeField
            End Get
            Set
                Me.propTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Summary() As String
            Get
                Return Me.summaryField
            End Get
            Set
                Me.summaryField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Descriptions() As Description()
            Get
                Return Me.descriptionsField
            End Get
            Set
                Me.descriptionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property PropImages() As PropImage()
            Get
                Return Me.propImagesField
            End Get
            Set
                Me.propImagesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Filename() As String
            Get
                Return Me.filenameField
            End Get
            Set
                Me.filenameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Locations() As Location()
            Get
                Return Me.locationsField
            End Get
            Set
                Me.locationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MinPrice() As Decimal
            Get
                Return Me.minPriceField
            End Get
            Set
                Me.minPriceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MaxPrice() As Decimal
            Get
                Return Me.maxPriceField
            End Get
            Set
                Me.maxPriceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Currency() As String
            Get
                Return Me.currencyField
            End Get
            Set
                Me.currencyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sleeps() As Integer
            Get
                Return Me.sleepsField
            End Get
            Set
                Me.sleepsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DoubleBeds() As Integer
            Get
                Return Me.doubleBedsField
            End Get
            Set
                Me.doubleBedsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TwinBeds() As Integer
            Get
                Return Me.twinBedsField
            End Get
            Set
                Me.twinBedsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SingleBeds() As Integer
            Get
                Return Me.singleBedsField
            End Get
            Set
                Me.singleBedsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cots() As Integer
            Get
                Return Me.cotsField
            End Get
            Set
                Me.cotsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bathrooms() As Integer
            Get
                Return Me.bathroomsField
            End Get
            Set
                Me.bathroomsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TV() As Boolean
            Get
                Return Me.tvField
            End Get
            Set
                Me.tvField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Satellite() As Boolean
            Get
                Return Me.satelliteField
            End Get
            Set
                Me.satelliteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Telephone() As Boolean
            Get
                Return Me.telephoneField
            End Get
            Set
                Me.telephoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cooker() As Boolean
            Get
                Return Me.cookerField
            End Get
            Set
                Me.cookerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Microwave() As Boolean
            Get
                Return Me.microwaveField
            End Get
            Set
                Me.microwaveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fridge() As Boolean
            Get
                Return Me.fridgeField
            End Get
            Set
                Me.fridgeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Freezer() As Boolean
            Get
                Return Me.freezerField
            End Get
            Set
                Me.freezerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Internet() As Boolean
            Get
                Return Me.internetField
            End Get
            Set
                Me.internetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CentralHeating() As Boolean
            Get
                Return Me.centralHeatingField
            End Get
            Set
                Me.centralHeatingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LinenProvided() As Boolean
            Get
                Return Me.linenProvidedField
            End Get
            Set
                Me.linenProvidedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AirConditioning() As Boolean
            Get
                Return Me.airConditioningField
            End Get
            Set
                Me.airConditioningField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Traffic() As String
            Get
                Return Me.trafficField
            End Get
            Set
                Me.trafficField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Seaside() As Boolean
            Get
                Return Me.seasideField
            End Get
            Set
                Me.seasideField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SightSeeing() As Boolean
            Get
                Return Me.sightSeeingField
            End Get
            Set
                Me.sightSeeingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tourist() As Boolean
            Get
                Return Me.touristField
            End Get
            Set
                Me.touristField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Romantic() As Boolean
            Get
                Return Me.romanticField
            End Get
            Set
                Me.romanticField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Relaxing() As Boolean
            Get
                Return Me.relaxingField
            End Get
            Set
                Me.relaxingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Activity() As Boolean
            Get
                Return Me.activityField
            End Get
            Set
                Me.activityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pets() As Boolean
            Get
                Return Me.petsField
            End Get
            Set
                Me.petsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenFire() As Boolean
            Get
                Return Me.openFireField
            End Get
            Set
                Me.openFireField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Garden() As Boolean
            Get
                Return Me.gardenField
            End Get
            Set
                Me.gardenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Patio() As Boolean
            Get
                Return Me.patioField
            End Get
            Set
                Me.patioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Balcony() As Boolean
            Get
                Return Me.balconyField
            End Get
            Set
                Me.balconyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrivatePool() As Boolean
            Get
                Return Me.privatePoolField
            End Get
            Set
                Me.privatePoolField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SharedPool() As Boolean
            Get
                Return Me.sharedPoolField
            End Get
            Set
                Me.sharedPoolField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TennisCourt() As Boolean
            Get
                Return Me.tennisCourtField
            End Get
            Set
                Me.tennisCourtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parking() As Boolean
            Get
                Return Me.parkingField
            End Get
            Set
                Me.parkingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Airport() As String
            Get
                Return Me.airportField
            End Get
            Set
                Me.airportField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AirportDistance() As String
            Get
                Return Me.airportDistanceField
            End Get
            Set
                Me.airportDistanceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property UserFields() As UserField()
            Get
                Return Me.userFieldsField
            End Get
            Set
                Me.userFieldsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MapLink() As String
            Get
                Return Me.mapLinkField
            End Get
            Set
                Me.mapLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lon() As Double
            Get
                Return Me.lonField
            End Get
            Set
                Me.lonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lat() As Double
            Get
                Return Me.latField
            End Get
            Set
                Me.latField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Extra() As String
            Get
                Return Me.extraField
            End Get
            Set
                Me.extraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Beach() As String
            Get
                Return Me.beachField
            End Get
            Set
                Me.beachField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sailing() As String
            Get
                Return Me.sailingField
            End Get
            Set
                Me.sailingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Swimming() As String
            Get
                Return Me.swimmingField
            End Get
            Set
                Me.swimmingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Walking() As String
            Get
                Return Me.walkingField
            End Get
            Set
                Me.walkingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cycling() As String
            Get
                Return Me.cyclingField
            End Get
            Set
                Me.cyclingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HorseRiding() As String
            Get
                Return Me.horseRidingField
            End Get
            Set
                Me.horseRidingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Skiing() As String
            Get
                Return Me.skiingField
            End Get
            Set
                Me.skiingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Golf() As String
            Get
                Return Me.golfField
            End Get
            Set
                Me.golfField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tennis() As String
            Get
                Return Me.tennisField
            End Get
            Set
                Me.tennisField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Climbing() As String
            Get
                Return Me.climbingField
            End Get
            Set
                Me.climbingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nonesmoking() As Boolean
            Get
                Return Me.nonesmokingField
            End Get
            Set
                Me.nonesmokingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InstantBooking() As Boolean
            Get
                Return Me.instantBookingField
            End Get
            Set
                Me.instantBookingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VillarentersIndex() As Integer
            Get
                Return Me.villarentersIndexField
            End Get
            Set
                Me.villarentersIndexField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExternalRef() As String
            Get
                Return Me.externalRefField
            End Get
            Set
                Me.externalRefField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/VillarentersWebService/villa_search")>  _
    Partial Public Class VillaResults
        
        Private numberOfRecordsField As Integer
        
        Private villasField() As Villa
        
        '''<remarks/>
        Public Property NumberOfRecords() As Integer
            Get
                Return Me.numberOfRecordsField
            End Get
            Set
                Me.numberOfRecordsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Villas() As Villa()
            Get
                Return Me.villasField
            End Get
            Set
                Me.villasField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub GoogleMapsLocatorsCompletedEventHandler(ByVal sender As Object, ByVal e As GoogleMapsLocatorsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GoogleMapsLocatorsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As marker()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),marker())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub VillaSearchCompletedEventHandler(ByVal sender As Object, ByVal e As VillaSearchCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VillaSearchCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As VillaResults
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),VillaResults)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub GetPropertyAvailabilityCompletedEventHandler(ByVal sender As Object, ByVal e As GetPropertyAvailabilityCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPropertyAvailabilityCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Availability
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Availability)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub GetPropertyReviewsCompletedEventHandler(ByVal sender As Object, ByVal e As GetPropertyReviewsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPropertyReviewsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PropertyReview
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PropertyReview)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub GetChildLocationsCompletedEventHandler(ByVal sender As Object, ByVal e As GetChildLocationsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetChildLocationsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ChildLocation
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ChildLocation)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub GetCountryListCompletedEventHandler(ByVal sender As Object, ByVal e As GetCountryListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCountryListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CountryList
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CountryList)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")>  _
    Public Delegate Sub VillaSearchV2CompletedEventHandler(ByVal sender As Object, ByVal e As VillaSearchV2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VillaSearchV2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As VillaResults
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),VillaResults)
            End Get
        End Property
    End Class
End Namespace
